name: RecipeManager
description: Add, edit or remove recipes and fuels
version: 2.14.4-dev
api-version: 1.13
authors: [haveric, ProgrammerDan, Digi]
website: http://dev.bukkit.org/server-mods/recipemanager/
dev-url: http://dev.bukkit.org/server-mods/recipemanager/
main: haveric.recipeManager.RecipeManager
softdepend: [Vault]
commands:
  rm:
    description: plugin info and available commands
    aliases: [recipemanager, rmhelp]
    usage: /<command>
    permission: recipemanager.command.rm
  rmrecipes:
    aliases: [recipe, recipes]
    description: find recipes that use the specified item
    usage: /<command> <material>:[data]:[amount] [i]
    permission: recipemanager.command.rmrecipes
  rmfinditem:
    aliases: [finditem]
    description: search for items by name or id
    usage: /<command> <name>
    permission: recipemanager.command.rmfinditem
  rmcheck:
    aliases: [checkrecipes]
    description: simulates loading recipe files to check for errors
    usage: /<command>
    permission: recipemanager.command.rmcheck
  rmreload:
    aliases: [reloadrecipes]
    description: reload recipes/settings/books/etc.
    usage: /<command>
    permission: recipemanager.command.rmreload
  rmreloadbooks:
    aliases: [reloadbooks]
    description: reload only recipe books
    usage: /<command>
    permission: recipemanager.command.rmreloadbooks
  rmextract:
    aliases: [rmimport, importrecipes, extractrecipes]
    description: makes all recipes from other plugins or mods into a text file to allow overriding and editing
    usage: /<command> [special]
    permission: recipemanager.command.rmextract
  rmgetbook:
    aliases: [getrecipebook]
    description: gives a recipe book
    usage: /<command> <title> [#<volume>]
    permission: recipemanager.command.rmgetbook
  rmbooks:
    aliases: [recipebooks]
    description: lists available recipe books
    usage: /<command>
    permission: recipemanager.command.rmbooks
  rmupdate:
    aliases: [rmcheckupdates]
    description: checks if there's a newer version available for the plugin
    usage: /<command>
    permission: recipemanager.command.rmupdate
  rmcreaterecipe:
    aliases: [createrecipe]
    description: creates a recipe from the leftmost 3x3 ingredients in an inventory and the held item as a result
    usage: /<command>
    permission: recipemanager.command.rmcreaterecipe
  rmruntests:
    description: used for testing the plugin
    usage: /<command>
    permission: recipemanager.command.rmruntests
permissions:
  recipemanager.craft:
    description: Toggles ability to craft all recipes
    default: true
  recipemanager.user:
    description: Gives basic user access
    default: true
    children:
      recipemanager.command.rm: true
      recipemanager.command.rmrecipes: true
      recipemanager.command.rmfinditem: true
  recipemanager.admin:
    description: Access to the admin commands
    default: op
    children:
      recipemanager.command.rmcheck: true
      recipemanager.command.rmreload: true
      recipemanager.command.rmreloadbooks: true
      recipemanager.command.rmextract: true
      recipemanager.command.rmgetbook: true
      recipemanager.command.rmbooks: true
      recipemanager.command.rmupdate: true
      recipemanager.command.rmcreaterecipe: true
  recipemanager.debugger:
    description: Get error messages when online
    default: op
  recipemanager.updatebooks:
    description: Allows player's recipe books to be updated
    default: true
  recipemanager.command.rm:
    description:
    default: true
  recipemanager.command.rmrecipes:
    description:
    default: true
  recipemanager.command.rmfinditem:
    description:
    default: true
  recipemanager.command.rmcheck:
    description:
    default: op
  recipemanager.command.rmreload:
    description:
    default: op
  recipemanager.command.rmreloadbooks:
    description:
    default: op
  recipemanager.command.rmextract:
    description:
    default: op
  recipemanager.command.rmgetbook:
    description:
    default: op
  recipemanager.command.rmbooks:
    description:
    default: op
  recipemanager.command.rmupdate:
    description:
    default: op
  recipemanager.command.rmcreaterecipe:
    description:
    default: op
  recipemanager.command.rmruntests:
    description:
    default: op
